# This is an example .release.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: lembra
before:
  hooks:
    - go mod tidy
builds:
  - id: lembra
    binary: lembra
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  prerelease: auto
universal_binaries:
  - replace: true
archives:
  files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: lembra
    homepage: https://github.com/lucasnevespereira/homebrew-tools
    tap:
      owner: lucasnevespereira
      name: homebrew-tools
      branch: main
    commit_author:
      name: lucasnevespereira
      email: pereiraneveslucas@gmail.com

# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj